### ISSUE TITLE
Teams Epic

### ISSUE THREAD

**Issue by clemsonmatt** [clemsonmatt/elliscfb-backend#5]
- [ ] Teams: Show details
- [ ] Teams: Conference standings (by week)
- [ ] Teams: Show stats (by week)
